[package]
name = "prover-elf-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bincode.workspace = true
sp1-prover = { workspace = true, features = [] }
