extend = [
    { path = "./scripts/make/Makefile.changelog.toml" },
    { path = "./scripts/make/Makefile.ci.toml" },
    { path = "./scripts/make/Makefile.contracts.toml" },
    { path = "./scripts/make/Makefile.e2e.toml" },
    { path = "./scripts/make/Makefile.elf.toml" },
    { path = "./scripts/make/Makefile.proto.toml" },
    { path = "./scripts/make/Makefile.test.toml" },
]

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true
default_to_workspace = false
