[package]
name = "aggchain-proof-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy-primitives.workspace = true
serde.workspace = true
sp1-core-executor.workspace = true

aggchain-proof-core.workspace = true

[lints]
workspace = true
