[package]
name = "aggchain-proof-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
tower = { workspace = true, features = ["timeout"] }
tracing.workspace = true

aggchain-proof-builder.workspace = true
aggkit-prover-types.workspace = true
proposer-service.workspace = true
prover-alloy.workspace = true
